name: My First Workflow

on: push

jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "My First Github Action"

            - name: list
              run: ls

            - name: Read file
              run: cat first-example.yml