name: My First Workflow

on: push

jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4    

            - name: Welcome message
              run: |
                echo "My First Github Action"
                ls -ltra
                cat README.md

            - name: list
              run: ls

            - name: Read file
              run: cat README.md