name: Multiple jobs

on: push

jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4    

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cosway cmd
              run: cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt
            
            - name: Sleep for 10sec
              run: sleep 10
            
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 10sec
              run: sleep 10

            - name: Test File exists
              run: grep -i "dragon" dragon.txt
    third-job: 
        needs: second-job
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat dragon.txt

            - name: List Repo files
              run: ls -ltra