name: Multiple jobs

on: push

jobs:
    first-job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4    

            - name: Install cowsay program
              run: sudo apt-get install cowsay -y

            - name: Execute cosway cmd
              run: cowsay -f dragon "Run for cover, I am a Dragon" >> dragon.txt
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-dragon
                path: dragon.txt
            
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
               name: my-dragon

            - name: Test File exists
              run: grep -i "dragon" dragon.txt
    third-job: 
        needs: second-job
        runs-on: ubuntu-latest
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
               name: my-dragon
               
            - name: Read file
              run: cat dragon.txt

            - name: List Repo files
              run: ls -ltra